#!/usr/bin/env python3
"""
Test Quest Creation Wizard
==========================

A simple script to test the quest creation functionality without GUI.
This will verify that:
1. Data model methods work correctly
2. Quest IDs are generated properly
3. Localisation and description entries are created
4. Quest entities are added to CFF structure
"""

import sys
from pathlib import Path

# Add the src directory to Python path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root / "src"))

def test_quest_creation():
    """Test quest creation functionality"""
    print("Testing Quest Creation Wizard functionality...")

    try:
        # Import required modules
        from TirganachReloaded.cff_editor.data_model import CFFDataModel
        from TirganachReloaded.cff_editor.widgets.quest_creation_wizard import QuestCreationWizard

        print("✓ Successfully imported required modules")

        # Initialize data model
        data_model = CFFDataModel()
        print("✓ Successfully initialized CFFDataModel")

        # Load some game data for testing
        print("Loading game data for testing...")
        data_paths = [
            Path("OriginalGameFiles/data/GameData.cff"),
            Path("OriginalGameFiles/Work/Data/GameData.cff"),
            Path("GameData.cff"),
            Path("src/TirganachReloaded/data/GameData.cff")
        ]

        game_data_loaded = False
        for path in data_paths:
            if path.exists():
                print(f"Loading game data from: {path}")
                if data_model.load_file(str(path)):
                    print("✓ Successfully loaded game data")
                    game_data_loaded = True
                    break
                else:
                    print("✗ Failed to load game data from this path")
            else:
                print(f"Game data not found at: {path}")

        if not game_data_loaded:
            print("⚠ No existing game data found - creating minimal structure for testing")
            # For testing purposes, we can create a minimal structure
            # This would normally require actual game data
            print("✗ Cannot proceed without game data - skipping quest creation test")
            return False

        # Test quest data (simulating wizard output)
        test_quest_data = {
            'quest_id': 9000,  # This would normally be generated by wizard
            'name': 'Test Quest Creation',
            'description': 'This is a test quest created by the automated test script.',
            'parent_id': 0,
            'order_index': 1,
            'platform': 'P1',
            'npc_id': 1001,
            'objectives': [
                {'type': 'KILL', 'description': 'Kill 5 Goblins'},
                {'type': 'COLLECT', 'description': 'Collect 3 Magic Stones'}
            ],
            'requirements': [
                {'type': 'LEVEL', 'description': 'Minimum Level 5'},
                {'type': 'ITEM', 'description': 'Have Sword of Testing'}
            ],
            'rewards': {
                'xp': 100,
                'gold': 50,
                'silver': 25,
                'copper': 10,
                'items': [1001, 1002]
            },
            'dialogues': [
                {'speaker': 'Quest Giver', 'text': 'Hello adventurer! I need your help.'},
                {'speaker': 'Player', 'text': 'What do you need me to do?'},
                {'speaker': 'Quest Giver', 'text': 'Please kill these goblins and collect some stones for me.'}
            ]
        }

        print("✓ Created test quest data")

        # Test quest creation
        print("Creating quest...")
        new_quest = data_model.create_quest(test_quest_data)

        if new_quest:
            print(f"✓ Successfully created quest with ID: {new_quest.quest_id}")
            print(f"  - Name ID: {new_quest.name_id}")
            print(f"  - Description ID: {new_quest.description_id}")
            print(f"  - Parent ID: {new_quest.parent_quest_id}")
            print(f"  - Order Index: {new_quest.order_index}")
        else:
            print("✗ Failed to create quest")
            return False

        # Verify quest was added to quests table
        if data_model.game_data and hasattr(data_model.game_data, 'quests'):
            quests_table = getattr(data_model.game_data, 'quests', None)
            if quests_table is not None:
                quest_found = False
                for quest in quests_table:
                    if quest.quest_id == test_quest_data['quest_id']:
                        quest_found = True
                        print(f"✓ Quest found in quests table: {quest}")
                        break

                if not quest_found:
                    print("✗ Quest not found in quests table")
                    return False
            else:
                print("✗ Quests table is None")
                return False
        else:
            print("✗ No quests table available")
            return False

        # Verify localisation entry was created
        if data_model.game_data and hasattr(data_model.game_data, 'localisation'):
            localisation_table = getattr(data_model.game_data, 'localisation', None)
            if localisation_table is not None:
                name_found = False
                for entry in localisation_table:
                    if entry.text_id == new_quest.name_id:
                        name_found = True
                        print(f"✓ Quest name found in localisation: '{entry.text}'")
                        break

                if not name_found:
                    print("✗ Quest name not found in localisation table")
                    return False
            else:
                print("✗ Localisation table is None")
                return False
        else:
            print("✗ No localisation table available")
            return False

        # Verify description entry was created
        if data_model.game_data and hasattr(data_model.game_data, 'advanced_descriptions'):
            descriptions_table = getattr(data_model.game_data, 'advanced_descriptions', None)
            if descriptions_table is not None:
                description_found = False
                for entry in descriptions_table:
                    if entry.description_id == new_quest.description_id:
                        description_found = True
                        print(f"✓ Quest description found in advanced_descriptions: '{entry.text}'")
                        break

                if not description_found:
                    print("✗ Quest description not found in advanced_descriptions table")
                    return False
            else:
                print("✗ Advanced descriptions table is None")
                return False
        else:
            print("✗ No advanced_descriptions table available")
            return False

        # Test ID generation
        text_id = data_model.generate_next_text_id()
        description_id = data_model.generate_next_description_id()
        print(f"✓ Generated next text ID: {text_id}")
        print(f"✓ Generated next description ID: {description_id}")

        print("\n🎉 All tests passed! Quest creation functionality is working correctly.")
        return True

    except Exception as e:
        print(f"✗ Test failed with error: {e}")
        import traceback
        traceback.print_exc()
        return False

def main():
    """Main test function"""
    print("=" * 60)
    print("QUEST CREATION WIZARD TEST")
    print("=" * 60)

    success = test_quest_creation()

    print("\n" + "=" * 60)
    if success:
        print("TEST RESULT: ✓ SUCCESS")
        print("The quest creation wizard is ready for use!")
    else:
        print("TEST RESULT: ✗ FAILED")
        print("Please check the errors above and fix them.")
    print("=" * 60)

    return 0 if success else 1

if __name__ == "__main__":
    sys.exit(main())