[pytest]
testpaths = src/tests
pythonpath = src
python_files = test_*.py
python_classes = Test*
python_functions = test_*
cache_dir = src/tests/test_data/.pytest_cache
addopts =
    --verbose
    --tb=short
    --basetemp=src/tests/test_data/tmp
markers =
    gui: marks tests that require GUI (deselect with '-m "not gui"')
    integration: marks tests that require external resources
    slow: marks tests as slow (deselect with '-m "not slow"')
