-- Custom Spell: Test Inferno Blast
-- Generated by SpellForce Spell Wizard
-- Date: 2025-01-01 12:00:00
-- Author: Spell Wizard Test

[301] = {
    includename="TestInfernoBlast",
    player=1,  -- Player can cast
    npc=0,     -- NPC cannot cast (custom spell)
    flag3=0,   -- Not an aura
    flag4=0,   -- Not a toggle
    flag5=1,
    flag6=0,
    flag7=0,
    flag8=0,
    effectscast={"CastFire"},
    effectsresolve={"ResolveFireExplosion"},
    effectsprojectile={"ProjectileFireBall"},
    effectstarget={"TargetBurn"},
    effectsovertime={""},
    spelllinebase=1,
}

