-- Visual Effects for Fireball
-- Auto-generated by Spell Wizard
-- Date: 2025-10-27 20:48:20

-- Cast Effect: Fire
EffectNew("CastFire", 0, "effectscast")
EffectAddEmitter("CastFire", 0, "flames")
EffectAddParticle("CastFire", 0, "fire_particle", 10)
EffectSetPosition("CastFire", 0, 0, 0, 0)
EffectSetLifetime("CastFire", 0, 1.5)
EffectSave("CastFire")

-- Projectile Effect: Fireball
EffectNew("ProjectileFireBall", 0, "effectsprojectile")
EffectAddEmitter("ProjectileFireBall", 0, "fire_trail")
EffectAddParticle("ProjectileFireBall", 0, "fire_particle", 15)
EffectSetPosition("ProjectileFireBall", 0, 0, 0, 0)
EffectSetLifetime("ProjectileFireBall", 0, 3.0)
EffectSave("ProjectileFireBall")

-- Resolve Effect: Fire Explosion
EffectNew("ResolveFireExplosion", 0, "effectsresolve")
EffectAddEmitter("ResolveFireExplosion", 0, "explosion")
EffectAddParticle("ResolveFireExplosion", 0, "fire_burst", 25)
EffectSetPosition("ResolveFireExplosion", 0, 0, 0, 0)
EffectSetLifetime("ResolveFireExplosion", 0, 2.0)
EffectSave("ResolveFireExplosion")

-- Target Effect: Burn
EffectNew("TargetBurn", 0, "effectstarget")
EffectAddEmitter("TargetBurn", 0, "burning")
EffectAddParticle("TargetBurn", 0, "flame_small", 5)
EffectSetPosition("TargetBurn", 0, 0, 1, 0)  -- On target
EffectSetLifetime("TargetBurn", 0, 5.0)
EffectSave("TargetBurn")

