
-- Sound events for Fireball
-- Generated by Spell Wizard

-- Cast sound
spell_fireball_cast = {
    File = "spell_fire_cast",
    Volume = 1.0,
    FallOffMin = 10,
    FallOffMax = 80,
}

-- Resolve/impact sound
spell_fireball_resolve = {
    File = "spell_hit_fireburst",
    Volume = 1.0,
    FallOffMin = 10,
    FallOffMax = 90,
}

-- Hit sound
spell_fireball_hit = {
    File = "spell_hit_explosion",
    Volume = 1.0,
    FallOffMin = 10,
    FallOffMax = 70,
}

