-- Generated Quest Script: Gather Supplies
-- Quest ID: 4002
-- Platform: P7


--
-- This script was generated by the SpellForce CFF Editor
-- Generated on: 2025-11-02 13:31:40


function CreateStateMachine(_Type, _PlatformId, _NpcId, _X, _Y)
BeginDefinition(_Type, _PlatformId, _NpcId, _X, _Y)

--------------------------------------------------------------------------
-- QUEST: GATHER SUPPLIES
-- ID: 4002
--------------------------------------------------------------------------

-- Quest Initialization
OnOneTimeEvent
{
    EventName = "Init_GatherSupplies",
    Conditions =
    {
        QuestState{QuestId = 4001, State = StateSolved}
    },
    Actions =
    {
        QuestBegin{QuestId = 4002}
        Outcry{
            NpcId = 0,
            String = "Collect necessary supplies",
            Color = ColorYellow
        }
    }
}

-- Quest Completion
OnOneTimeEvent
{
    EventName = "Complete_GatherSupplies",
    Conditions =
    {
        QuestState{QuestId = 4002, State = StateActive}
    },
    Actions =
    {
        QuestSolve{QuestId = 4002}
        SetRewardFlagTrue{Name = "Quest4002Reward"}
    }
}

-- Quest Rewards (typically in GdsQuestRewards.lua)
-- Quest4002Reward = {
--     XP = {0},
--     Money = {Gold = 0, Silver = 0, Copper = 0},
--     Items = {}
-- }


EndDefinition()
end
