-- Generated Quest Script: Find the Guide
-- Quest ID: 4003
-- Platform: P7


--
-- This script was generated by the SpellForce CFF Editor
-- Generated on: 2025-11-02 13:31:40


function CreateStateMachine(_Type, _PlatformId, _NpcId, _X, _Y)
BeginDefinition(_Type, _PlatformId, _NpcId, _X, _Y)

--------------------------------------------------------------------------
-- QUEST: FIND THE GUIDE
-- ID: 4003
--------------------------------------------------------------------------

-- Quest Initialization
OnOneTimeEvent
{
    EventName = "Init_FindtheGuide",
    Conditions =
    {
        QuestState{QuestId = 4002, State = StateSolved}
    },
    Actions =
    {
        QuestBegin{QuestId = 4003}
        Outcry{
            NpcId = 0,
            String = "Locate the experienced guide",
            Color = ColorYellow
        }
    }
}

-- Quest Completion
OnOneTimeEvent
{
    EventName = "Complete_FindtheGuide",
    Conditions =
    {
        QuestState{QuestId = 4003, State = StateActive}
    },
    Actions =
    {
        QuestSolve{QuestId = 4003}
        SetRewardFlagTrue{Name = "Quest4003Reward"}
    }
}

-- Quest Rewards (typically in GdsQuestRewards.lua)
-- Quest4003Reward = {
--     XP = {0},
--     Money = {Gold = 0, Silver = 0, Copper = 0},
--     Items = {}
-- }


EndDefinition()
end
