-- Generated Quest Script: The Lost Sword
-- Quest ID: 1001
-- Platform: P7


--
-- This script was generated by the SpellForce CFF Editor
-- Generated on: 2025-11-02 13:31:40


function CreateStateMachine(_Type, _PlatformId, _NpcId, _X, _Y)
BeginDefinition(_Type, _PlatformId, _NpcId, _X, _Y)

--------------------------------------------------------------------------
-- QUEST: THE LOST SWORD
-- ID: 1001
--------------------------------------------------------------------------

-- Quest Initialization
OnOneTimeEvent
{
    EventName = "Init_TheLostSword",
    Conditions =
    {
        AvatarLevel{Level = 5}
    },
    Actions =
    {
        QuestBegin{QuestId = 1001}
        Outcry{
            NpcId = 100,
            String = "Find the legendary sword in the ancient ruins",
            Color = ColorYellow
        }
    }
}

-- Objective 1: Defeat the Guardian
OnOneTimeEvent
{
    EventName = "TheLostSword_Objective1",
    Conditions =
    {
        QuestState{QuestId = 1001, State = StateActive},
        -- TODO: Add specific condition for: Defeat the Guardian
    },
    Actions =
    {
        Outcry{
            NpcId = 0,
            String = "Objective completed: Defeat the Guardian",
            Color = ColorGreen
        }
    }
}

-- Objective 2: Collect the Ancient Sword
OnOneTimeEvent
{
    EventName = "TheLostSword_Objective2",
    Conditions =
    {
        QuestState{QuestId = 1001, State = StateActive},
        -- TODO: Add specific condition for: Collect the Ancient Sword
    },
    Actions =
    {
        Outcry{
            NpcId = 0,
            String = "Objective completed: Collect the Ancient Sword",
            Color = ColorGreen
        }
    }
}

-- Quest Completion
OnOneTimeEvent
{
    EventName = "Complete_TheLostSword",
    Conditions =
    {
        QuestState{QuestId = 1001, State = StateActive}
        FigureIsDead{Tag = "Guardian"}
        PlayerHasItem{ItemId = 101, Amount = 1}
    },
    Actions =
    {
        QuestSolve{QuestId = 1001}
        SetRewardFlagTrue{Name = "Quest1001Reward"}
        Outcry{
            NpcId = 0,
            String = "Quest completed: The Lost Sword!",
            Color = ColorGreen
        }
    }
}

-- Quest Rewards (typically in GdsQuestRewards.lua)
-- Quest1001Reward = {
--     XP = {1000},
--     Money = {Gold = 50, Silver = 0, Copper = 0},
--     Items = {201, 202}
-- }


EndDefinition()
end
