-- Generated Quest Script: The Great Adventure
-- Quest ID: 4001
-- Platform: P7


--
-- This script was generated by the SpellForce CFF Editor
-- Generated on: 2025-11-02 13:31:40


function CreateStateMachine(_Type, _PlatformId, _NpcId, _X, _Y)
BeginDefinition(_Type, _PlatformId, _NpcId, _X, _Y)

--------------------------------------------------------------------------
-- QUEST: THE GREAT ADVENTURE
-- ID: 4001
--------------------------------------------------------------------------

-- Quest Initialization
OnOneTimeEvent
{
    EventName = "Init_TheGreatAdventure",
    Conditions =
    {
        -- No prerequisites
    },
    Actions =
    {
        QuestBegin{QuestId = 4001}
        Outcry{
            NpcId = 0,
            String = "Embark on an epic journey",
            Color = ColorYellow
        }
    }
}

-- Quest Completion
OnOneTimeEvent
{
    EventName = "Complete_TheGreatAdventure",
    Conditions =
    {
        QuestState{QuestId = 4001, State = StateActive}
        -- TODO: Complete all sub-quests
    },
    Actions =
    {
        QuestSolve{QuestId = 4001}
        SetRewardFlagTrue{Name = "Quest4001Reward"}
        Outcry{
            NpcId = 0,
            String = "Quest completed: The Great Adventure!",
            Color = ColorGreen
        }
    }
}

-- Quest Rewards (typically in GdsQuestRewards.lua)
-- Quest4001Reward = {
--     XP = {0},
--     Money = {Gold = 0, Silver = 0, Copper = 0},
--     Items = {}
-- }


EndDefinition()
end
