"""
SpellForce Spell Creation System - Lua Script Exporter
"""

import os
from typing import Dict, Any, List
from datetime import datetime

from ..models import SpellCreationData, SpellLevel


class SpellLuaExporter:
    """Exports spell data to Lua scripts for SpellForce"""

    def __init__(self, output_dir: str = "exported_spells"):
        self.output_dir = output_dir
        self.ensure_output_dir()

    def ensure_output_dir(self):
        """Create output directory if it doesn't exist"""
        os.makedirs(self.output_dir, exist_ok=True)

    def export_spell(self, spell_data: SpellCreationData) -> Dict[str, str]:
        """
        Export spell to Lua files

        Returns:
            Dict mapping file paths to Lua code content
        """
        files = {}

        # 1. sql_spellline.lua entry
        files["script/sql_spellline.lua"] = self.generate_spellline_entry(spell_data)

        # 2. Visual effects script
        vfx_filename = f"object/object_effect_{spell_data.internal_name.lower()}.lua"
        files[vfx_filename] = self.generate_vfx_script(spell_data)

        # 3. Sound event registration
        files["script/DrwSound.lua"] = self.generate_sound_entry(spell_data)

        # 4. Spell stats data (for CFF integration)
        stats_filename = f"data/spell_stats_{spell_data.internal_name.lower()}.lua"
        files[stats_filename] = self.generate_spell_stats(spell_data)

        return files

    def generate_spellline_entry(self, spell_data: SpellCreationData) -> str:
        """Generate sql_spellline.lua entry"""

        # Map magic school to spell line base
        school_base_map = {
            "WHITE": 0,
            "FIRE": 1,
            "ICE": 2,
            "BLACK": 3,
            "MENTAL": 4,
            "EARTH": 5
        }
        spell_line_base = school_base_map.get(spell_data.magic_school.name, 0)

        lua_code = f"""-- Custom Spell: {spell_data.spell_name}
-- Generated by SpellForce Spell Wizard
-- Date: {spell_data.created_date}
-- Author: {spell_data.author}

[{spell_data.spell_line_id}] = {{
    includename="{spell_data.internal_name}",
    player=1,  -- Player can cast
    npc=0,     -- NPC cannot cast (custom spell)
    flag3=0,   -- Not an aura
    flag4=0,   -- Not a toggle
    flag5=1,
    flag6=0,
    flag7=0,
    flag8=0,
    effectscast={{"{spell_data.vfx_cast}"}},
    effectsresolve={{"{spell_data.vfx_resolve}"}},
    effectsprojectile={{"{spell_data.vfx_projectile}"}},
    effectstarget={{"{spell_data.vfx_target}"}},
    effectsovertime={{"{spell_data.vfx_overtime}"}},
    spelllinebase={spell_line_base},
}}

"""
        return lua_code

    def generate_vfx_script(self, spell_data: SpellCreationData) -> str:
        """Generate visual effects Lua script"""

        lua_code = f"""-- Visual Effects for {spell_data.spell_name}
-- Auto-generated by Spell Wizard
-- Date: {spell_data.created_date}

"""

        # Cast Effect
        if spell_data.vfx_cast:
            lua_code += self.get_vfx_template(spell_data.vfx_cast, "cast")
            lua_code += f'EffectSave("{spell_data.vfx_cast}")\n\n'

        # Projectile Effect
        if spell_data.vfx_projectile and spell_data.has_projectile:
            lua_code += self.get_vfx_template(spell_data.vfx_projectile, "projectile")
            lua_code += f'EffectSave("{spell_data.vfx_projectile}")\n\n'

        # Resolve Effect
        if spell_data.vfx_resolve:
            lua_code += self.get_vfx_template(spell_data.vfx_resolve, "resolve")
            lua_code += f'EffectSave("{spell_data.vfx_resolve}")\n\n'

        # Target Effect
        if spell_data.vfx_target:
            lua_code += self.get_vfx_template(spell_data.vfx_target, "target")
            lua_code += f'EffectSave("{spell_data.vfx_target}")\n\n'

        # Overtime Effect (for buffs/debuffs)
        if spell_data.vfx_overtime:
            lua_code += self.get_vfx_template(spell_data.vfx_overtime, "overtime")
            lua_code += f'EffectSave("{spell_data.vfx_overtime}")\n\n'

        return lua_code

    def get_vfx_template(self, effect_name: str, effect_type: str) -> str:
        """Get VFX template code for a given effect"""

        # This is a simplified version - in a real implementation,
        # you'd have a library of VFX templates
        templates = {
            "CastFire": """-- Cast Effect: Fire
EffectNew("CastFire", 0, "effectscast")
EffectAddEmitter("CastFire", 0, "flames")
EffectAddParticle("CastFire", 0, "fire_particle", 10)
EffectSetPosition("CastFire", 0, 0, 0, 0)
EffectSetLifetime("CastFire", 0, 1.5)
""",
            "CastIce": """-- Cast Effect: Ice
EffectNew("CastIce", 0, "effectscast")
EffectAddEmitter("CastIce", 0, "frost")
EffectAddParticle("CastIce", 0, "ice_particle", 8)
EffectSetPosition("CastIce", 0, 0, 0, 0)
EffectSetLifetime("CastIce", 0, 1.5)
""",
            "ProjectileFireBall": """-- Projectile Effect: Fireball
EffectNew("ProjectileFireBall", 0, "effectsprojectile")
EffectAddEmitter("ProjectileFireBall", 0, "fire_trail")
EffectAddParticle("ProjectileFireBall", 0, "fire_particle", 15)
EffectSetPosition("ProjectileFireBall", 0, 0, 0, 0)
EffectSetLifetime("ProjectileFireBall", 0, 3.0)
""",
            "ResolveFireExplosion": """-- Resolve Effect: Fire Explosion
EffectNew("ResolveFireExplosion", 0, "effectsresolve")
EffectAddEmitter("ResolveFireExplosion", 0, "explosion")
EffectAddParticle("ResolveFireExplosion", 0, "fire_burst", 25)
EffectSetPosition("ResolveFireExplosion", 0, 0, 0, 0)
EffectSetLifetime("ResolveFireExplosion", 0, 2.0)
""",
            "TargetBurn": """-- Target Effect: Burn
EffectNew("TargetBurn", 0, "effectstarget")
EffectAddEmitter("TargetBurn", 0, "burning")
EffectAddParticle("TargetBurn", 0, "flame_small", 5)
EffectSetPosition("TargetBurn", 0, 0, 1, 0)  -- On target
EffectSetLifetime("TargetBurn", 0, 5.0)
""",
        }

        return templates.get(effect_name, f"-- Custom effect: {effect_name}\n-- TODO: Implement custom VFX\n")

    def generate_sound_entry(self, spell_data: SpellCreationData) -> str:
        """Generate DrwSound.lua entry"""

        internal_lower = spell_data.internal_name.lower()

        lua_code = f"""
-- Sound events for {spell_data.spell_name}
-- Generated by Spell Wizard

-- Cast sound
spell_{internal_lower}_cast = {{
    File = "{spell_data.sfx_cast}",
    Volume = 1.0,
    FallOffMin = 10,
    FallOffMax = 80,
}}

"""

        if spell_data.sfx_projectile:
            lua_code += f"""-- Projectile sound
spell_{internal_lower}_projectile = {{
    File = "{spell_data.sfx_projectile}",
    Volume = 0.8,
    FallOffMin = 5,
    FallOffMax = 100,
}}

"""

        lua_code += f"""-- Resolve/impact sound
spell_{internal_lower}_resolve = {{
    File = "{spell_data.sfx_resolve}",
    Volume = 1.0,
    FallOffMin = 10,
    FallOffMax = 90,
}}

"""

        if spell_data.sfx_hit:
            lua_code += f"""-- Hit sound
spell_{internal_lower}_hit = {{
    File = "{spell_data.sfx_hit}",
    Volume = 1.0,
    FallOffMin = 10,
    FallOffMax = 70,
}}

"""

        return lua_code

    def generate_spell_stats(self, spell_data: SpellCreationData) -> str:
        """Generate spell stats data for CFF integration"""

        lua_code = f"""-- Spell Stats for {spell_data.spell_name}
-- Generated by Spell Wizard
-- This file contains the stat progression data

local {spell_data.internal_name}Stats = {{
    spell_name = "{spell_data.spell_name}",
    spell_line_id = {spell_data.spell_line_id},
    magic_school = "{spell_data.magic_school.name}",
    spell_type = "{spell_data.spell_type.value}",
    description = "{spell_data.description}",
    target_type = "{spell_data.target_type.value}",
    has_projectile = {str(spell_data.has_projectile).lower()},
    base_range = {spell_data.base_range},
    aoe_radius = {spell_data.aoe_radius},
    duration = {spell_data.duration},
    special_effects = {{""" + ", ".join(f'"{effect}"' for effect in spell_data.special_effects) + """},
    levels = {{
"""

        # Add level data
        for level in spell_data.levels:
            lua_code += f"""        [{level.level}] = {{
            damage_min = {level.damage_min},
            damage_max = {level.damage_max},
            mana_cost = {level.mana_cost},
            cooldown = {level.cooldown},
            cast_time = {level.cast_time},
            range = {level.range},
            aoe_radius = {level.aoe_radius},
            duration = {level.duration},
        }},
"""

        lua_code += f"""    }},
}}

return {spell_data.internal_name}Stats
"""

        return lua_code

    def export_to_files(self, spell_data: SpellCreationData) -> List[str]:
        """
        Export spell to actual files on disk

        Returns:
            List of exported file paths
        """
        files = self.export_spell(spell_data)
        exported_files = []

        for file_path, content in files.items():
            full_path = os.path.join(self.output_dir, file_path)

            # Create subdirectories if needed
            os.makedirs(os.path.dirname(full_path), exist_ok=True)

            # Write file
            with open(full_path, 'w', encoding='utf-8') as f:
                f.write(content)

            exported_files.append(full_path)

        return exported_files

    def generate_test_spell_book(self, spell_data: SpellCreationData) -> str:
        """Generate item definition for a test spell book"""

        # Item ID for spell book (9800 range for custom items)
        item_id = 9800 + spell_data.spell_line_id - 300

        item_def = f"""-- Test Spell Book: {spell_data.spell_name}
-- Item ID: {item_id}
-- Generated by Spell Wizard

local TestSpellBook{spell_data.internal_name} = {{
    item_id = {item_id},
    item_name = "Spell Book: {spell_data.spell_name}",
    item_type = "spell_book",
    icon_id = 1234,  -- Spell book icon
    teaches_spell = {spell_data.spell_line_id},
    spell_levels = {spell_data.num_levels},
    description = "{spell_data.description}",

    -- Spell stats preview
    spell_stats = {{
        school = "{spell_data.magic_school.name}",
        type = "{spell_data.spell_type.value}",
        max_level = {spell_data.num_levels},
        level_1_damage = "{spell_data.levels[0].damage_min}-{spell_data.levels[0].damage_max}",
        level_max_damage = "{spell_data.levels[-1].damage_min}-{spell_data.levels[-1].damage_max}",
    }},
}}

return TestSpellBook{spell_data.internal_name}
"""

        return item_def


class SpellValidator:
    """Validates spell data before export"""

    def __init__(self):
        self.errors = []
        self.warnings = []

    def validate(self, spell_data: SpellCreationData) -> tuple[List[str], List[str]]:
        """Validate spell data and return errors/warnings"""
        self.errors = []
        self.warnings = []

        # Check spell name
        if not spell_data.spell_name.strip():
            self.errors.append("Spell name is required")

        # Check internal name
        if not spell_data.internal_name.strip():
            self.errors.append("Internal name is required")
        elif " " in spell_data.internal_name:
            self.errors.append("Internal name cannot contain spaces")

        # Check level progression
        if len(spell_data.levels) != spell_data.num_levels:
            self.errors.append(f"Level count mismatch: expected {spell_data.num_levels}, got {len(spell_data.levels)}")

        # Validate level data
        for i, level in enumerate(spell_data.levels):
            if level.damage_min > level.damage_max:
                self.errors.append(f"Level {i+1}: Min damage ({level.damage_min}) > Max damage ({level.damage_max})")

            if level.mana_cost < 0:
                self.errors.append(f"Level {i+1}: Mana cost cannot be negative")

            if level.cooldown < 0:
                self.errors.append(f"Level {i+1}: Cooldown cannot be negative")

            if level.cast_time < 0:
                self.errors.append(f"Level {i+1}: Cast time cannot be negative")

            # Warnings for potentially unbalanced spells
            if level.mana_cost == 0 and (level.damage_min > 0 or level.damage_max > 0):
                self.warnings.append(f"Level {i+1}: Free spell with damage - potential balance issue")

            if level.damage_max > 1000:
                self.warnings.append(f"Level {i+1}: Very high damage ({level.damage_max})")

            # Check scaling consistency
            if i > 0:
                prev_level = spell_data.levels[i - 1]
                if level.damage_max <= prev_level.damage_max and level.damage_max > 0:
                    self.warnings.append(f"Level {i+1}: Damage not increasing from previous level")

        # Check spell line ID uniqueness (simplified check)
        if spell_data.spell_line_id < 300 or spell_data.spell_line_id > 999:
            self.errors.append("Spell Line ID must be between 300-999 for custom spells")

        # Check VFX references (simplified)
        vfx_effects = [spell_data.vfx_cast, spell_data.vfx_projectile,
                      spell_data.vfx_resolve, spell_data.vfx_target, spell_data.vfx_overtime]
        for vfx in vfx_effects:
            if vfx and vfx.startswith("Custom"):
                self.warnings.append(f"VFX '{vfx}' is marked as custom - ensure it exists in game files")

        return self.errors, self.warnings

    def get_balance_score(self, spell_data: SpellCreationData) -> Dict[str, Any]:
        """Calculate balance score for the spell"""
        if not spell_data.levels:
            return {"score": 0, "category": "Unknown", "issues": ["No level data"]}

        # Use highest level for balance calculation
        max_level = spell_data.levels[-1]

        # Calculate damage per mana (DPM)
        avg_damage = (max_level.damage_min + max_level.damage_max) / 2
        dpm = avg_damage / max_level.mana_cost if max_level.mana_cost > 0 else 0

        # Calculate damage per second
        effective_time = max_level.cast_time + max_level.cooldown
        dps = avg_damage / effective_time if effective_time > 0 else 0

        # Power rating (arbitrary scale)
        power_rating = (dpm * 10 + dps * 5) / 2

        # Categorize
        if power_rating < 20:
            category = "Weak"
        elif power_rating < 40:
            category = "Balanced"
        elif power_rating < 60:
            category = "Strong"
        else:
            category = "Overpowered"

        return {
            "damage_per_mana": round(dpm, 2),
            "damage_per_second": round(dps, 2),
            "power_rating": round(power_rating, 1),
            "balance_category": category,
        }


# Test functions
def test_exporter():
    """Test the Lua exporter"""
    from ..models import SpellCreationData, MagicSchool, SpellType, TargetType, ScalingMode

    # Create sample spell
    spell_data = SpellCreationData(
        spell_name="Test Fireball",
        internal_name="TestFireball",
        magic_school=MagicSchool.FIRE,
        spell_type=SpellType.ATTACK,
        description="A test fireball spell",
        target_type=TargetType.SINGLE,
        has_projectile=True,
        base_range=25.0,
        aoe_radius=0.0,
        duration=0.0,
        special_effects=["burn"],
        num_levels=5,
        scaling_mode=ScalingMode.LINEAR,
        vfx_cast="CastFire",
        vfx_projectile="ProjectileFireBall",
        vfx_resolve="ResolveFireExplosion",
        vfx_target="TargetBurn",
        vfx_overtime="",
        sfx_cast="spell_fire_cast",
        sfx_projectile="",
        sfx_resolve="spell_hit_fireburst",
        sfx_hit="spell_hit_explosion",
        spell_line_id=300,
        created_date="2025-01-01 12:00:00",
        author="Test User"
    )

    # Apply scaling
    spell_data.apply_scaling()

    # Export
    exporter = SpellLuaExporter("test_export")
    files = exporter.export_to_files(spell_data)

    print(f"Exported {len(files)} files:")
    for file_path in files:
        print(f"  - {file_path}")

    # Validate
    validator = SpellValidator()
    errors, warnings = validator.validate(spell_data)

    print(f"\nValidation results:")
    print(f"Errors: {len(errors)}")
    for error in errors:
        print(f"  - {error}")

    print(f"Warnings: {len(warnings)}")
    for warning in warnings:
        print(f"  - {warning}")

    balance = validator.get_balance_score(spell_data)
    print(f"\nBalance score: {balance}")


if __name__ == "__main__":
    test_exporter()