-- Custom Spell: Fireball
-- Generated by SpellForce Spell Wizard
-- Date: 2025-10-27 20:48:20
-- Author: Spell Wizard Template

[301] = {
    includename="Fireball",
    player=1,  -- Player can cast
    npc=0,     -- NPC cannot cast (custom spell)
    flag3=0,   -- Not an aura
    flag4=0,   -- Not a toggle
    flag5=1,
    flag6=0,
    flag7=0,
    flag8=0,
    effectscast={"CastFire"},
    effectsresolve={"ResolveFireExplosion"},
    effectsprojectile={"ProjectileFireBall"},
    effectstarget={"TargetBurn"},
    effectsovertime={""},
    spelllinebase=1,
}

