-- Spell Stats for Test Fireball
-- Generated by Spell Wizard
-- This file contains the stat progression data

local TestFireballStats = {
    spell_name = "Test Fireball",
    spell_line_id = 300,
    magic_school = "FIRE",
    spell_type = "attack",
    description = "A test fireball spell",
    target_type = "single",
    has_projectile = true,
    base_range = 25.0,
    aoe_radius = 0.0,
    duration = 0.0,
    special_effects = {"burn"},
    levels = {{
        [1] = {
            damage_min = 0,
            damage_max = 0,
            mana_cost = 10,
            cooldown = 3.0,
            cast_time = 1.5,
            range = 20.0,
            aoe_radius = 0.0,
            duration = 0.0,
        },
        [2] = {
            damage_min = 10,
            damage_max = 12,
            mana_cost = 13,
            cooldown = 2.9,
            cast_time = 1.5,
            range = 20.5,
            aoe_radius = 0.0,
            duration = 0.0,
        },
        [3] = {
            damage_min = 20,
            damage_max = 24,
            mana_cost = 16,
            cooldown = 2.8,
            cast_time = 1.5,
            range = 21.0,
            aoe_radius = 0.0,
            duration = 0.0,
        },
        [4] = {
            damage_min = 30,
            damage_max = 36,
            mana_cost = 19,
            cooldown = 2.7,
            cast_time = 1.5,
            range = 21.5,
            aoe_radius = 0.0,
            duration = 0.0,
        },
        [5] = {
            damage_min = 40,
            damage_max = 48,
            mana_cost = 22,
            cooldown = 2.6,
            cast_time = 1.5,
            range = 22.0,
            aoe_radius = 0.0,
            duration = 0.0,
        },
    },
}

return TestFireballStats
