# GitHub Pages Configuration for SpellForce Modding Documentation

# Theme
theme: jekyll-theme-cayman

# Site Settings
title: SpellForce Modding Documentation
description: Comprehensive guides for modding SpellForce Platinum Edition
baseurl: "/SpellSmut"
url: "https://alexerlewein.github.io"

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Enable GitHub metadata
repository: AlexErlewein/SpellSmut

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Custom header banner
banner_image: /SpellSmut/assets/images/banner.jpg

# Favicon (browser tab icon)
favicon: /SpellSmut/assets/images/favicon.ico
